omada-controller-helm:
#  service:
#    annotations:
#      external-dns.alpha.kubernetes.io/hostname: omada.home.arpa
  nodeSelector:
    # Mongo DB 8 requires AVX
    feature.node.kubernetes.io/cpu-cpuid.AVX: "true"
  persistence:
    data:
      storageClassName: rook-cephfs
    logs:
      storageClassName: rook-cephfs
#    extraVolumeMounts:
#      - name: omada-backups
#        # Determined by omada...
#        mountPath: /opt/tplink/EAPController/data/autobackup
#    extraVolumes:
#      - name: omada-backups
#        persistentVolumeClaim:
#          claimName: omada-backup-pvc