apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-public
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: traefik
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: traefik-public
      valueFiles:
        - values-public.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-private
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    path: traefik
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: traefik-private
      valueFiles:
        - values-private.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik