apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-private
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 38.0.1
    helm:
      releaseName: traefik-private
      valueFiles:
        - values-private.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik